input_cloud_topic: "/ouster/points"
input_odom_topic: "/odometry/filtered"
output_marker_topic: "/cluster_centers"

# Filtering parameters
azimuth_min: -2.35619  # -135 degrees in radians
azimuth_max: 2.35619   # 135 degrees in radians
z_min: -0.8
z_max: -0.5
x_min: -5.0
x_max: 5.0
y_min: -5.0
y_max: 5.0

# Noise removal parameters
mean_k: 50
stddev_mul_thresh: 1.0

# Clustering parameters
cluster_tolerance: 0.1
min_cluster_size: 5
max_cluster_size: 10000

# DA parameters
association_threshold: 1.0  # Threshold for associating clusters