odom_topic: "/robot/dlo/odom_node/odom"
robot_frame: "robot/base_link"
trajectory_topic: "trajectory"
frame_id: "map"
pathtosavelandmarkcsv: "config/landmark.csv"
pathtoloadlandmarkcsv: "config/landmark.csv"
savetaglocation: true
usepriortagtable: false
batch_optimisation: true
total_tags: 626
transformation_search_range: 0.1
add2graph_threshold: 0.2
timewindow: 50
maxfactors: 400
useprunebytime: true
useprunebysize: false

# Loop closure
surroundingKeyframeSize: 50
historyKeyframeSearchRadius: 15.0
historyKeyframeSearchTimeDiff: 300.0
historyKeyframeSearchNum: 25
historyKeyframeFitnessScore: 0.3

# Keyframe info
distanceThreshold: 1
rotationThreshold: 5
  
noise_models:
  odometry:
    - 0.01
    - 1
    - 0.01
  prior:
    - 0.1
    - 0.3
    - 0.1
  bearing_range:
    - 0.1
    - 0.8
  point:
    - 0.1
    - 0.1
  loopClosureNoise:
    - 0.1
    - 0.1

# Camera parameters
camera_parameters:
  xyTrans_lcam_baselink: [0, 0, 1.5708]  # pi/2 in radians
  xyTrans_mcam_baselink: [0, 0, 0]
  xyTrans_rcam_baselink: [0, 0, -1.5708]  # -pi/2 in radians

# Camera subscribers
camera_subscribers:
  lCam_subscriber:
    topic: "/l/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  rCam_subscriber:
    topic: "/r/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  mCam_subscriber:
    topic: "/m/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
