odom_topic: "/robot/dlo/odom_node/odom"
robot_frame: "robot/base_link"
trajectory_topic: "trajectory"
frame_id: "map"
pathtosavelandmarkcsv: "config/landmark.csv"
pathtoloadlandmarkcsv: "config/landmark.csv"
savetaglocation: false
usepriortagtable: true
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
maxfactors: 400 # maximum number of poses in the factor graph
useprunebysize: true

# Loop closure
surroundingKeyframeSize: 50
historyKeyframeSearchRadius: 15.0
historyKeyframeSearchTimeDiff: 300.0
historyKeyframeSearchNum: 25
historyKeyframeFitnessScore: 0.3

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius

# Keyframe info
distanceThreshold: 0.5
rotationThreshold: 5
  
noise_models:
  odometry:
    - 0.1
    - 1
    - 0.1
  prior:
    - 0.1
    - 0.3
    - 0.1
  bearing_range:
    - 0.001
    - 0.008
  point:
    - 0.001
    - 0.001
  loopClosureNoise:
    - 0.01
    - 0.01

# Camera parameters
camera_parameters:
  xyTrans_lcam_baselink: [0, 0, 1.57079632679]  # pi/2 in radians
  xyTrans_mcam_baselink: [0, 0, 0]
  xyTrans_rcam_baselink: [0, 0, -1.57079632679]  # -pi/2 in radians

# Camera subscribers
camera_subscribers:
  lCam_subscriber:
    topic: "/l/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  rCam_subscriber:
    topic: "/r/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  mCam_subscriber:
    topic: "/m/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
