odom_topic: "/antobot_robot/odom"
odom_frame: "robot/odom"
robot_frame: "robot/base_link"
trajectory_topic: "trajectory"
map_frame_id: "TagMap"
pathtosavelandmarkcsv: "config/landmark.csv"
pathtoloadlandmarkcsv: "config/afteroptimisation.csv"
ud_frame: "robot/base_link"
savetaglocation: false
usepriortagtable: true
batch_optimisation: true
total_tags: 1000
add2graph_threshold: 0.2
maxfactors: 200 # maximum number of poses in the factor graph
useprunebysize: true # no point of using it with ISAM2
useisam2: false # true for ISAM2, false for SAM

# Particle initilisation condition 
N_particles: 1000
usePFinitialise: false
PFWaitTime: 5
rngVar: 0.2
brngVar: 0.1

# Loop closure, dont apply LC when pruning is enabled
useloopclosure: false
historyKeyframeSearchRadius: 3 # minimum historyKeyframeSearchRadius meters to be considered loopclosured
historyKeyframeSearchNum: 40 # loopclosure only checking historyKeyframeSearchNum frames apart poses
requiredReobservedLandmarks: 3 

# Stationary threshold
stationary_position_threshold: 0.05 # 5cm
stationary_rotation_threshold: 0.1 # 0.1radius

# Keyframe info, no need to use it if in isam2 mode
usekeyframe: false
distanceThreshold: 0.5
rotationThreshold: 5
  
noise_models:
  odometry:
    - 3
    - 30
    - 3
  prior:
    - 0.1
    - 0.3
    - 0.1
  bearing_range:
    - 0.1
    - 0.8
  point:
    - 0.001
    - 0.001
  loopClosureNoise:
    - 0.5
    - 5
    - 0.5

# Camera parameters
camera_parameters:
  xyTrans_lcam_baselink: [0, 0, 1.57079632679]  # pi/2 in radians
  xyTrans_mcam_baselink: [0, 0, 0]
  xyTrans_rcam_baselink: [0, 0, -1.57079632679]  # -pi/2 in radians

# Camera subscribers
camera_subscribers:
  lCam_subscriber:
    topic: "/l/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  rCam_subscriber:
    topic: "/r/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"
  mCam_subscriber:
    topic: "/m/tag_detections"
    type: "apriltag_ros/AprilTagDetectionArray"
    data_format: "struct"